### ISSUE TITLE
LinearLayout::Place signature

### ISSUE THREAD

**Issue by houcha** [gle8098/succotash#2]
https://github.com/gle8098/succotash/blob/f2b2343d0b70ee7ce2459daa47f6d243bb701bab/src/linear_layout.hpp#L16
Давай остановимся на такой сигнатуре ввиду большей очевидности:
```cpp
void LinearLayout::Place(std::vector<View*>& views, const sf::RectangleShape& area)
```
Вызовы тогда будут выглядеть так:
```cpp
layout->Place(sons_, shape_);
```
А не:
```cpp
layout->Place(this);
```

**Comment by gle8098** [comment]
Merged in #3
